### ISSUE TITLE
too loose libPoco check

### ISSUE THREAD

**Issue by chipitsine** [yandex/clickhouse-odbc#1]
libPoco is tested against shared libraries, so test passes, but actual linking (against static libPoco) fails:

https://travis-ci.org/chipitsine/clickhouse-odbc/jobs/221513786

I guess, either libPocoxxx should be tested for static libraries or linkng must be done using -Bshared

**Comment by chipitsine** [comment]
up?

**Comment by artpaul** [comment]
Hi!

Do you have good solution for this problem? 

Problem not only in tests. I think that would be better to embed poco into this repo (as you done in your fork) and build it from source with driver without installing to system dirs.

**Comment by chipitsine** [comment]
the "good" depends on how you define it.
either static or dynamic linking might be considered as a "good" solution.

if we want to stick with static linking, so we need to modify Cmake files (to check for static Poco). Also, static Poco is not usually available through repos, so I added it as git submodule.

linking against dynamic Poco is much simpler, it is available everywhere, no need to add as a submodule


also, I wished to add AppVeyor build for clickhouse-odbc, it seems, it assumes "Poco" is located at the level above of clickhouse-odbc folder. Probably, adding as a git submodule will fit AppVeyor build as well.

**Comment by artpaul** [comment]
We decide to add poco as submodule.

**Comment by chipitsine** [comment]
and, I guess, link statically?
so, should I open a PR for CMake change?

**Comment by artpaul** [comment]
> and, I guess, link statically?
yes

> so, should I open a PR for CMake change?
yes, please. I put poco to contrib/poco dir.

**Comment by chipitsine** [comment]
https://github.com/yandex/clickhouse-odbc/pull/3

I'll add more things (like contrib/poco, travis-ci) later
