### ISSUE TITLE
Cannot change the timeout for Tableau

### ISSUE THREAD

**Issue by jadephung** [yandex/clickhouse-odbc#101]
Somehow when I connect Tableau to clickhouse server through the ODBC there's not timeout configuration and any query taking longer than 30s will pop up bad connection error. Please help to resolve this problem.

**Comment by jadephung** [comment]
@proller

**Comment by aadim** [comment]
you should use the Timeout setting for the ODBC connection, here's a example for Windows ODBC Manager:

![image](https://user-images.githubusercontent.com/16644384/43942676-9d2097ca-9c81-11e8-93ff-b0a948cb731f.png)

Though there's an issue with newer driver versions #70 as the driver seems to ignore this option.

**Comment by jadephung** [comment]
yes I changed that timeout but in Tableau desktop it basically just terminate the connection after 30 seconds and pop up bad connection message. Should I actually just download version before 10.3 to bypass this error? Otherwise I was trying to rebuilt the source code with extended default timeout but it can't be built. Not sure what problem and I'm very in need of this ODBC.

**Comment by aadim** [comment]
the problem is with the ODBC driver, you should use this one https://github.com/yandex/clickhouse-odbc/releases/tag/2017-11-07

**Comment by jadephung** [comment]
it works!!!! Thank you so much!!!!
