### ISSUE TITLE
query timeout with tableau ODBC

### ISSUE THREAD

**Issue by pandey957** [yandex/clickhouse-odbc#102]
I getting query timeout error after 30 seconds. 

I tried setting `timeout=100` with connection details but it does nothing. 

Here is my tableau connection string: 

 <connection class='genericodbc' dbname='default' odbc-connect-string-extras='PROTO=http;timeout=60' odbc-dbms-name='ClickHouse' odbc-driver='ClickHouse Unicode' odbc-dsn='ml' odbc-suppress-connection-pooling='' odbc-use-connection-pooling='' port='8123' server='localhost' username='default'>
<connection-customization class='genericodbc' enabled='false' version='10.5'>

**Comment by blinkov** [comment]
See 
https://github.com/yandex/clickhouse-odbc/issues/101#issuecomment-411994817 for workaround

**Comment by proller** [comment]
Should be fixed here
https://github.com/yandex/clickhouse-odbc/commit/7e6f0a583256e45c8d6fc527298bfa5ac8b2c24b
