### ISSUE TITLE
isql symbol lookup error: undefined symbol: SQLGetPrivateProfileString

### ISSUE THREAD

**Issue by rkinwork** [yandex/clickhouse-odbc#109]
Hi. I've built driver on CentOS7 (ODBC - Release 2018-08-16)

after building and adjusting odbc.ini and odbcinst.ini files and invoking isql I'm getting this error:

`isql clickhouse -v`
`isql: symbol lookup error: /home/centos/clhsdrv/clickhouse-odbc/build/driver/libclickhouseodbc.so: undefined symbol: SQLGetPrivateProfileString`

content of the isql trace

>[ODBC][12110][1534501009.511514][__handles.c][460]
                Exit:[SQL_SUCCESS]
                        Environment = 0x1334750
[ODBC][12110][1534501009.511671][SQLAllocHandle.c][377]
                Entry:
                      	Handle Type = 2
                        Input Handle = 0x1334750
[ODBC][12110][1534501009.511694][SQLAllocHandle.c][493]
                Exit:[SQL_SUCCESS]
                        Output Handle = 0x1335080
[ODBC][12110][1534501009.511713][SQLConnect.c][3721]
                Entry:
                      	Connection = 0x1335080
                        Server Name = [clickhouse_47][length = 13 (SQL_NTS)]
                        User Name = [NULL]
                        Authentication = [NULL]
                UNICODE Using encoding ASCII 'UTF-8' and UNICODE 'UCS-2LE'

Output of the make execution is [attached](https://github.com/yandex/clickhouse-odbc/files/2296850/clickhousecompile.txt)

Also I've built same release on ubuntu and it works normally

**Comment by rkinwork** [comment]
Output of command
[centos@user]$ nm -D /usr/local/lib/libodbcinst.so | grep SQLGetPrivateProfileString
0000000000004db0 T SQLGetPrivateProfileString
0000000000005400 T SQLGetPrivateProfileStringW

**Comment by rkinwork** [comment]
Only I've found that are problems with compiling 

`>>> ldd -d -r libclickhouseodbc.so`
	linux-vdso.so.1 =>  (0x00007ffcc2f64000)
	libodbc.so.2 => /usr/local/lib/libodbc.so.2 (0x00007f9896148000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f9895e3b000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f9895a6e000)
	/lib64/ld-linux-x86-64.so.2 (0x00005561a003e000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f989586a000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f989564d000)
undefined symbol: SQLGetPrivateProfileString	(./libclickhouseodbc.so)

I've all paths in ENV variables $PATH : 

/usr/local/lib:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/centos/.local/bin:/home/centos/bin:/usr/local/lib:/usr/local/lib64
and 

and  $LD_LIBRARY_PATH

/usr/local/lib:/usr/local/lib64

**Comment by sunsingerus** [comment]
You may want to take a look into [this repo](https://github.com/Altinity/clickhouse-odbc-rpm) for RPM build script or into [this repo](https://packagecloud.io/Altinity/clickhouse) for ready-to-use RPMs

**Comment by sunsingerus** [comment]
clickhouse-odbc is tested on CentOS 7 only so far. In case you need CentOS 6 it may require some modifications

**Comment by rkinwork** [comment]
@sunsingerus thank you for your RPMs! I've installed it on CentOS and it's working good
