### ISSUE TITLE
Tableau ODBC - connection refused

### ISSUE THREAD

**Issue by Jor-Da** [yandex/clickhouse-odbc#113]
I'm trying to connect Tableau (2018.2) to my Clickhouse db running on AWS EC2. Using the latest 64-bit ODBC driver with public DNS of the EC2 instance as host, default as user and db, port 8123, PROTO=http.

Connection to EC2 works however no tables are found by Tableau and when I try a Custom SQL query from Tableau I get the following error:

> Connection refused:
Generic ODBC requires additional configuration. The driver and DSN (data source name) must be installed and configured to match the connection.
Unable to connect using the DSN named "ClickHouse". Check that the DSN exists and is a valid connection.

Running `Sudo netstat -tulpn` I get:

> Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.1:9009          0.0.0.0:*               LISTEN      1585/clickhouse-ser
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1529/sshd
tcp        0      0 127.0.0.1:8123          0.0.0.0:*               LISTEN      1585/clickhouse-ser
tcp        0      0 127.0.0.1:9000          0.0.0.0:*               LISTEN      1585/clickhouse-ser
tcp6       0      0 ::1:9009                :::*                    LISTEN      1585/clickhouse-ser
tcp6       0      0 :::22                   :::*                    LISTEN      1529/sshd
tcp6       0      0 ::1:8123                :::*                    LISTEN      1585/clickhouse-ser
tcp6       0      0 ::1:9000                :::*                    LISTEN      1585/clickhouse-ser
udp        0      0 0.0.0.0:68              0.0.0.0:*                           1134/dhclient
udp        0      0 0.0.0.0:46847           0.0.0.0:*                           1134/dhclient
udp6       0      0 :::45433                :::*                                1134/dhclient

**Comment by blinkov** [comment]
Sounds like you are trying to remotely connect to ClickHouse that listens only localhost.
Try uncommenting this listen_host directives https://github.com/yandex/ClickHouse/blob/9975960d77e0745ebec07b69129ac816a9738439/dbms/programs/server/config.xml#L66-L69 in your /etc/clickhouse-server/config.xml and restart click house-server.

**Comment by blinkov** [comment]
Probably the clickhouse-server process could not start at all, check what's going on in `/var/log/clickhouse-server/*`

**Comment by Jor-Da** [comment]
We can chalk this up to a bit of a brain fart:

> `<listen_host>::</listen_host> <listen_host>0.0.0.0</listen_host>`

Uncommenting both those lines results in a conflict. Now I've left only the second one uncommented and it works as expected :)
