### ISSUE TITLE
TIMESTAMPADD not supported 

### ISSUE THREAD

**Issue by Jor-Da** [yandex/clickhouse-odbc#114]
Trying do vs. LY comparisons in Tableau and getting the following error in Tableau:

> Bad Connection: Tableau could not connect to the data source.

> Cannot interpret 'ᴺᵁᴸᴸ' as double: invalid stod argument
SELECT `stock_denorm`.`municipality` AS `municipality`,
  `stock_denorm`.`region` AS `region`,
  SUM((CASE WHEN ({fn TIMESTAMPADD(SQL_TSI_DAY,CAST({fn TRUNCATE((-1 * (EXTRACT(DAY FROM {fn TIMESTAMPADD(SQL_TSI_DAY,-1,`stock_denorm`.`createddate`)}) - 1)),0)} AS INTEGER),CAST({fn TIMESTAMPADD(SQL_TSI_DAY,-1,`stock_denorm`.`createddate`)} AS DATE))} = {ts '2018-08-01 00:00:00'}) THEN (COALESCE(`stock_denorm`.`soldstock`, 0) * COALESCE(`stock_denorm`.`volume`, 0)) ELSE NULL END)) AS `sum_Calculation_437975098872115206_ok`
FROM `stock_denorm`
GROUP BY `municipality`,
  `region`

Rewriting the query for better readability and running directly in clickhouse-client (SQL_TSI_DAY replaced with 'day'):
`SELECT
    municipality,
    region,
    SUM(multiIf(TIMESTAMPADD('day', CAST(TRUNCATE(-1 * (toDayOfMonth(TIMESTAMPADD('day', -1, createddate)) - 1), 0), 'INTEGER'), CAST(TIMESTAMPADD('day', -1, createddate), 'DATE')) = '2018-06-01 00:00:00', COALESCE(soldstock, 0) * COALESCE(volume, 0), NULL)) AS stockly
FROM stock_denorm
GROUP BY
    municipality,
    region
`

Yields the following response: 

> Received exception from server (version 18.10.3):
Code: 46. DB::Exception: Received from localhost:9000, 127.0.0.1. DB::Exception: Unknown function TIMESTAMPADD.

**Comment by blinkov** [comment]
Which versions of ClickHouse and ODBC driver do you use? It looks like it might work:
https://github.com/yandex/clickhouse-odbc/search?q=TIMESTAMPADD&unscoped_q=TIMESTAMPADD

**Comment by Jor-Da** [comment]
Hi Ivan,

I was running 18.10.3 with the driver released August 22nd. I have now tried it with the latest driver and it works as expected!
