### ISSUE TITLE
Tableau compatibility Issues : View type are not exposed correctly 

### ISSUE THREAD

**Issue by TH-HA** [yandex/clickhouse-odbc#123]
I'm using Tableau 18.3 beta with Clickhouse version :18.12.13 and Clickhouse ODBC driver version:1.0.0.20180903

I'm using a view to access a table with states. This view contain a datetime field ( which is correctly view from other tools such as tabix ...). 
When using the view in tableau , the date_time field in exposed as a string.

Thanks

**Comment by aadim** [comment]
Did you try to change the data type in Tableau?

**Comment by TH-HA** [comment]
Hello , 
Sorry for the late answer. 
Yes i 've tried to change it into tableau. 
But as a string data type is returned , it's not straightforward 
       not complex either , you have to create a computed field which is parsing the date but it's not working as tableau is trying to convert the string field into timestamp using SQL statement. 

 but in any case it make things more complex  ( typically you have to manage timezone if both place tableau and CH ) and really less efficient as filtering capabilities of CH are not used. 

Regards

**Comment by proller** [comment]
Can you show minimal table structure where it can be reproduced ?

**Comment by TH-HA** [comment]
I don't know if it's relevant but to share a sample with you i 've done the following test : 
using "select now()" works fine into tableau , looking at the datatype ( "select toTypeName(now())" )  return a simple "DateTime". 
When doing the same with my view ( i have the same issue with the table by the way ) , return a DateTime with timezone ( select toTypeName(date_time) from demo.geotweethour limit 1 return  DateTime('Zulu') ).
Can it be the introduction of TimeZone which is breaking the compatibility with ODBC ?

The view structure is the following : 
CREATE VIEW demo.geotweethour (
  date_time DateTime('Zulu'),
  id UInt64,
  longitude Float64,
  latitude Float64
) AS
SELECT
  date_time,
  uniqCombinedMerge(id) AS id,
  longitude,
  latitude
FROM
  demo.tweethour
GROUP BY
  date_time,
  longitude,
  latitude

**Comment by TH-HA** [comment]
I've switched to the latest version of the drivers and server version 18.14.9 and it seems to work fine now. 
Thanks for the support ( on this issue and other one on the function mapping ) . 
Regards
