### ISSUE TITLE
Tableau compatibility Issues : mathematical function not working

### ISSUE THREAD

**Issue by TH-HA** [yandex/clickhouse-odbc#124]
I'm using Tableau 18.3 beta with Clickhouse version :18.12.13 and Clickhouse ODBC driver version:1.0.0.20180903

When using calculated fields in tableau with the Log function tableau report the following error (i've simplified the request for reporting the bug ) 
I 've tried with many of the function present in tableau ( COS , CEILING , LOG )  , they all produce the same result. 
 : 

HTTP status code: 500 Received error: Code: 62, e.displayText() = DB::Exception: Syntax error: failed at position 55 (line 1, col 55): {fn LOG10(`Custom_SQL_Query`.`z`)} ELSE NULL END)) AS `sum_Calculation_1621295916296810500_ok`, SUM(toInt64(`Custom_SQL_Query`.`x`)) AS `sum_x_ok`, SUM(toIn. Unrecognized token, e.what() = DB::Exception
SELECT SUM((CASE WHEN `Custom_SQL_Query`.`z` > 0 THEN {fn LOG10(`Custom_SQL_Query`.`z`)} ELSE NULL END)) AS `sum_Calculation_1621295916296810500_ok`,
  SUM({fn CONVERT(`Custom_SQL_Query`.`x`, SQL_BIGINT)}) AS `sum_x_ok`,
  SUM({fn CONVERT(`Custom_SQL_Query`.`y`, SQL_BIGINT)}) AS `sum_y_ok`
FROM (
  select c+1 as x,c+2 as y,c as z,arrayJoin(array(1,2,3,4) )as c
) `Custom_SQL_Query`
HAVING (COUNT(1) > 0)

**Comment by TH-HA** [comment]
I don't know if it make sense ( as i 'm far from being an expert on ODBC , i'm mainly java/jdbc) 
But can i try to extends the class : driver/escaping/escape_sequences.cpp to add all the missing standard SQL keyword ( which can be remapped on clickhouse function ) to improve the compatibility ?

Thanks in advance

**Comment by proller** [comment]
https://github.com/yandex/clickhouse-odbc/pull/127

**Comment by TH-HA** [comment]
Thanks , it's working fine now . 
Regards
