### ISSUE TITLE
При использовании функции ODBC для Postgres в столбец типа Date приходит NULL

### ISSUE THREAD

**Issue by yutrostin** [yandex/clickhouse-odbc#140]
При попытке экспорта таблицы из Postgres с помощью функции ODBC в поле типа Date приходит либо NULL, либо 0000-00-00, либо 1970-01-01. Использую версию v1.0.0.20181017

**Comment by proller** [comment]
Опишите пожалуйста подробнее как воспроизвести проблему.

**Comment by yutrostin** [comment]
Допустим, в Postgres есть таблица users, где есть столбцы:
- created_at *DateTime* NOT NULL
- birthday *Date*
- name *Varchar*

Настроен DSN postgres_database для подключения. В КХ выполняете команду:
`SELECT * FROM odbc('DSN=postgres_database', 'users')`

При ее выполнении в КХ приедут данные из таблицы users, со столбцами created_at и name все будет хорошо, а вот в birthday приедет NULL.

**Comment by proller** [comment]
Тогда это проблема в самом сервере который живет тут - https://github.com/yandex/ClickHouse
А этот репозиторий для odbc драйвера с помощью которого можно подключаться к серверу.

**Comment by yutrostin** [comment]
Окей, спасибо. Закрываю issue и завожу новый там
