### ISSUE TITLE
Implement WITH TOTALS support

### ISSUE THREAD

**Issue by nightweb** [yandex/clickhouse-odbc#144]
Hi,

Clickhouse ODBC doesn't support with totals query. Can we add implement in ResultSet (as implemented in the JDBC driver)

**Comment by proller** [comment]
this should be implemented at clickhouse-server side and wirks for all types of connections.
Please open issue in https://github.com/yandex/ClickHouse/issues

Also some  WITH TOTALS queries already implemented - 
https://github.com/yandex/ClickHouse/blob/master/dbms/tests/queries/0_stateless/00388_enum_with_totals.sql
Please describe exactly what you want (with query samples)
