### ISSUE TITLE
Connect from Tableau Server for Linux

### ISSUE THREAD

**Issue by yurifal** [yandex/clickhouse-odbc#152]
Hi dev team, 

Here below is the description of the problem 
with connecting Tableau Server for Linux to CH via ODBC.

The environment: 
(CH) -- ClickHouse v.18.16.1 in Docker container on macOS Mojave 10.14.2.
(TD) -- Tableau Desktop v.2018.3.2 on macOS Mojave 10.14.2.
(TS) -- Tableau Server for Linux v.2018.3.2 on Ubuntu 16.04 LTS.

The datasource was created in TD using the ODBC connection to CH 
(database = default, table = ontime), and then published to TS.

[The successful **connection** was established from TS to CH](https://www.dropbox.com/s/xy5zhe4wnx362j0/Screenshot%202019-01-14%20at%2014.31.00.png?dl=0),
so there is no problem with the networking between them.

But the attempt to create a New Workbook based on this datasource 
(using a Web Edit mode of TS) [failed with error](https://www.dropbox.com/s/ex59xlhljtb2epf/Screenshot%202019-01-14%20at%2014.31.51.png?dl=0).

On the other side, a New Workbook could be **successfully created** (in Web Edit mode) 
using a ***JDBC connection** to that same CH instance / database / table.
[Here is the screenshot of the successfully created workbook/view](https://www.dropbox.com/s/y5tig0v5en10pgd/Screenshot%202019-01-14%20at%2014.34.14.png?dl=0).
So the working connection to CH has been established using the JDBC driver (at least).

The main difference between the ODBC and JDBC connections 
(at least at the initial connection / probe phase) is that 
the JDBC connection request includes the **schema = default** as an attribute, 
but the ODBC connection requests the **schema = null** (or **schema = ' '**), 
which leads to the DB::Exception (error 62). 

Please find [the reference to the TS ziplogs](https://www.dropbox.com/s/7xru40gul38yuna/ziplogs.zip?dl=0).
Please take a look at the **tabprotosrv_vizqlserver_1-0.txt** log (in the vizqlserver folder), 
the Event IDs **1585** and **1588** as examples of the faulty ODBC requests. 

Please compare to the successful request via JDBC driver 
(this one is using TS Dataserver process as a sql-proxy).

The request was initiated by VizQL Server (as captured by Event ID **20910** 
in the **nativeapi_vizqlserver_1-0_2019_01_12_00_00_00.txt** vizqlserver log), 
then translated and executed by the Dataserver (as captured by Event **1673** 
in the **tabprotosrv_dataserver_1-0.txt** dataserver log).

The suggestion would be to include the **schema = default** meta-data 
in the connection configuration info (don't know if it makes any sense for ODBC, though).

Yours,
Yuri

BTW, the workbook (using this datasource) was created in TD and published to TS.
As expected, any attempt to open any view on the TS would failed (either with error, 
or stalled at the login). [Here is a screenshot of an unsuccessful login attempt](https://www.dropbox.com/s/pg9uxt5g2szyrw9/Screenshot%202019-01-14%20at%2014.28.55.png?dl=0) 
when opening the view (Sheet 7 Date) from this workbook on TS.

**Comment by proller** [comment]
Can you show your odbc.ini with Clickhouse datasource? (without passwords)

Also you can try enable clickhouse-odbc logging:
Add to connection settings:
Trace=1
TraceFile=/temp/clickhouse-odbc.log 

in log you can find lines like 
```../driver/statement.cpp:72 POST localhost/query?database=default&default_format=ODBCDriver2 body=select......```
interesting part is database=default - is it 'default' ?

**Comment by yurifal** [comment]
Here is the copy of /etc/odbc.ini
```
[ODBC Data Sources]
ClickHouse = ClickHouse

[ClickHouse]
Driver    = /usr/lib/x86_64-linux-gnu/odbc/libclickhouseodbc.so
server    = 192.168.1.42
password  = xxxxxxx
port      = 8123
database  = default
uid       = default
# sslmode = allow
trace     = 1
tracefile = /tmp/clickhouse-odbc.log
```

and a copy of /etc/odbcinst.ini
(with other drivers installed, too)
```
[ODBC Drivers]
PostgreSQL Unicode=Installed
Vertica=Installed
EXASolution Driver=Installed
ClickHouse=Installed

[PostgreSQL Unicode]
Description=ODBC for PostgreSQL
Driver=/opt/tableau/tableau_driver/postgresql-odbc/psqlodbcw.so
FileUsage=1

[Vertica]
Driver=/opt/vertica/lib64/libverticaodbc.so

[EXASolution Driver]
Driver=/opt/exasol/libexaodbc-uo2214lv2.so

[ClickHouse]
Driver=/usr/lib/x86_64-linux-gnu/odbc/libclickhouseodbc.so
```

The ODBC connection from TS to CH was successful 
using the published datasource (same as before).

Below is a screenshot with the error 
when trying to create a new workbook 
based on the published datasource:
<img width="283" alt="screenshot 2019-02-08 at 16 56 01" src="https://user-images.githubusercontent.com/2496788/52483069-0b9e0300-2bc4-11e9-8edc-938a93106c59.png">

There are no traces of 
`../driver/statement.cpp:72 POST localhost/query?database=default&default_format=ODBCDriver2 body=select......`
in the /tmp/clickhouse-odbc.log file -- 
that's because of the (faulty) connection process 
didn't even come close to querying the actual data, 
it breaks right after the bunch of probing queries.

Here is a link to the log file:
[clickhouse-odbc.log.zip](https://github.com/yandex/clickhouse-odbc/files/2847699/clickhouse-odbc.log.zip)

There are two (positive) controls:

1. The connection is successful from macOS using the same datasource.
The trace file in this case does indeed contain the above statement:
`../driver/statement.cpp:72 POST 192.168.1.42/query?database=default&default_format=ODBCDriver2 body=select......`

2. The ODBC connection to the other RDBMS (namely Exasol) 
is successful on the **server** using the published datasource -- 
to confirm a general ODBC connectivity is working on the server.

**Comment by icaptnbob** [comment]
@proller , I have been trying to use TS on Linux with CH ODBC. 

I also get a similar error to in TS to that shown by @yurifal above:
```
HTTP status code: 400
Received error:
Code: 62, e.displayText() = DB::Exception: Syntax error: failed at position 27 (line 2, col 18): 
The table "voice_cube" does not exist.
Generic ODBC requires additional configuration. The driver and DSN (data source name) must be installed and configured to match the connection.
Unable to connect using the DSN named "clickhouse_ansi". Check that the DSN exists and is a valid connection.
```

It seems an @ character is appended to the query statement, which causes many or most of the preparation statements to fail.
In the odbc.log trace file, there are many of these types of error after each connection attempt.
```
/opt/temp/clickhouse-odbc/driver/odbc.cpp:79 SQLPrepare statement_text_size=9 statement_text=SELECT 1
/opt/temp/clickhouse-odbc/driver/odbc.cpp:90 query(9) = [SELECT 1^@]
/opt/temp/clickhouse-odbc/driver/odbc.cpp:99 SQLExecute
/opt/temp/clickhouse-odbc/driver/statement.cpp:72 POST 172.18.180.28/query?database=rdw&default_format=ODBCDriver2 body=SELECT 1^@
/opt/temp/clickhouse-odbc/driver/statement.cpp:100 HTTP status code: 400
Received error:
Code: 62, e.displayText() = DB::Exception: Syntax error: failed at position 9: ^@. Unrecognized token, e.what() = DB::Exception


/opt/temp/clickhouse-odbc/driver/utils.h:29 Exception: HTTP status code: 400
Received error:
Code: 62, e.displayText() = DB::Exception: Syntax error: failed at position 9:
```

I have a similar ODBC configuration to that shown by @yurifal above.
Tableau server 2018.3.2 (20183.18.1214.0808) on CentOS
Clickhouse ODBC drivers VERSION=1.0.0.20181017
We tried to compile a later copy from the newer release tags, but those didn't work at all.

I can connect and successfully run queries on the CH database using isql -v clickhouse using ANSI.
The unicode versions fail to connect at all with isql, returning an error: "[ISQL]ERROR: Could not SQLConnect"
With the same version of Clickhouse ODBC ANSI on Windows, the same reports work correctly in TS.


Do you have a later copy of the drivers for Linux which I can test with?

**Comment by DrMitzi** [comment]
Hi and thanks for all the details!
I have a similar problem, on TS (2018.3.2 (20183.18.1214.0808) 64-bit Linux)
I've created a workbook with a live CH ODBC data source on TD. Published it to TS, but when I try to access a view, I get the following error message, although my server administrator already installed the Clickhouse ODBC drivers to the Server.
```[unixODBC][Driver Manager]Can't open lib 'ClickHouse Unicode' : file not found Generic ODBC requires additional configuration. The driver and DSN (data source name) must be installed and configured to match the connection. Unable to connect using the DSN named &quot;Clickhouse_w&quot;. Check that the DSN exists and is a valid connection.```
@yurifal I'm very curious to find out how you published an existing workbook and it worked, or what's the difference between what you did and what I did. As you can see, my connection in the published workbook is unsuccessful.
![image](https://user-images.githubusercontent.com/32938882/54829869-a86db900-4cb7-11e9-94a5-a6961e657807.png)

**Comment by yurifal** [comment]
Hi @DrMitzi 

Please try to install ODBC driver with **libiodbc** (instead of **unixodbc**).
And even if the test connection is successful, it's of no use (with TS for Linux).

Yours,
Yuri

**Comment by theyoshi1986** [comment]
I am very far from ++, but i noticed that in statement_text_size=9 but in statement_text=SELECT 1 its only 8 chars. Maybe that is the reason of error?

**Comment by DrMitzi** [comment]
@yurifal Thanks for the suggestion! Do you mean on the desktop, on the server, or on both?

**Comment by yurifal** [comment]
On the server (Linux) or on the desktop (macOS). 
Windows has its own ODBC manager.

**Comment by DrMitzi** [comment]
@yurifal Thanks a lot for your advice. Thanks to it, our Server admin started digging a bit into the ODBC driver configurations, and found a missing space in the driver name. 
This is the correct configuration:
```[Clickhouse Unicode]
Description=Clickhouse UNICODE ODBC Driver
Driver=/usr/lib/x86_64-linux-gnu/odbc/libclickhouseodbcw.so
Setup=/usr/lib/x86_64-linux-gnu/odbc/libclickhouseodbcw.so
UsageCount=1```
TS expects it to be called `Clickhouse Unicode` (with a space between the two words)
Now it's working, yay!

**Comment by hohaftf** [comment]
@DrMitzi Could you share a link to the issue?

**Comment by theyoshi1986** [comment]
Hi all, @proller fixed that bug. Connection is successful

**Comment by yurifal** [comment]
Yep, can connect (TS 2019.1.2, Ubuntu 16.04). 
Thanks @proller !
