### ISSUE TITLE
Проблема с LowCardinality

### ISSUE THREAD

**Issue by DNEGREEV** [yandex/clickhouse-odbc#157]
При попытке запросить данные атрибута в таблице с типом LowCardinality получаю ошибку.
An error occurred while loading the data.
invalid map<K, T> key

Подскажите, это баг драйвера, или нужно какие-то настройки подкрутить?

**Comment by proller** [comment]
Неправильный быстрофикс: https://github.com/yandex/clickhouse-odbc/pull/158
Правильный, но со следующим релизом ClickHouse: https://github.com/yandex/ClickHouse/pull/4381

**Comment by DNEGREEV** [comment]
Извиняюсь за глупый вопрос, чтобы пощупать изменения нужно ждать новый релиз драйвера?
