### ISSUE TITLE
ODBC Manager and Tableau don't see an installed clickhouse-odbc on macOS

### ISSUE THREAD

**Issue by madcat1991** [yandex/clickhouse-odbc#162]
I'm trying to configure a ClickHouse data source in Tableau Desktop on macOS. To install the ODBC driver I used the guide provided here: https://github.com/yandex/clickhouse-odbc/blob/master/MACOS.md#simple-install-macos-brew

The files are successfully installed:
```
[tural@turals-mbp-3 ~]$ ls -al /usr/local/opt/clickhouse-odbc/lib/*
-r--r--r--  1 tural  admin  5685016 19 мар 16:39 /usr/local/opt/clickhouse-odbc/lib/libclickhouseodbc.dylib
lrwxr-xr-x  1 tural  admin       23 19 мар 16:39 /usr/local/opt/clickhouse-odbc/lib/libclickhouseodbc.so -> libclickhouseodbc.dylib
-r--r--r--  1 tural  admin  5692984 19 мар 16:39 /usr/local/opt/clickhouse-odbc/lib/libclickhouseodbcw.dylib
lrwxr-xr-x  1 tural  admin       24 19 мар 16:39 /usr/local/opt/clickhouse-odbc/lib/libclickhouseodbcw.so -> libclickhouseodbcw.dylib
```

I also set up the `~/.odbc.ini` to:
```
[ClickHouse]
Driver = /usr/local/opt/clickhouse-odbc/lib/libclickhouseodbcw.dylib
# Optional settings:
#server = localhost
#password = 123456
#port = 8123
#database = default
#uid = default
#sslmode = require
```

However, neither ODBC Manager nor Tableau Desktop don't see the new DSN. I also unable to add a driver through ODBC Manager. What did I miss?

**Comment by madcat1991** [comment]
Ok, to make it visible one should add the path to the Driver into `odbcinst.ini`. In my case it is: `/Users/tural/Library/ODBC/odbcinst.ini`.

**Comment by getkot** [comment]
> https://github.com/yandex/clickhouse-odbc/blob/master/MACOS.md#simple-install-macos-brew

Hello! This link is 404 now((
Have u a new link with driver files? PLS

**Comment by traceon** [comment]
@getkot no, for macOS you need to compile the driver manually. The process is straightforward: https://github.com/ClickHouse/clickhouse-odbc#building-from-sources

**Comment by nlc10** [comment]
@traceon @madcat1991 

I'm following the steps mentioned here (https://github.com/ClickHouse/clickhouse-odbc#building-from-sources) but not with much luck. 
Below are the steps I'm following:

brew install git cmake make poco openssl icu4c libiodbc 

git clone --recursive https://github.com:ClickHouse/clickhouse-odbc.git

cd clickhouse-odbc
mkdir build
cd build

cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DOPENSSL_ROOT_DIR=$(brew --prefix)/opt/openssl -DICU_ROOT=$(brew --prefix)/opt/icu4c ..

cmake --build . --config RelWithDebInfo
cmake --build . --config RelWithDebInfo --target package

After this, I tried to open the iODBC Manager, but I don't see any drivers installed. I'm a beginner at MacOS and also not a developer (just an analyst trying to connect click house to tableau), so please let me know where I'm going wrong.  Kindly requesting you to help me with the same.

**Comment by nlc10** [comment]
@traceon @madcat1991 Hi Guys, Kindly request you guys to guide me on this.

**Comment by traceon** [comment]
@nlc10 If you were not able to compile the driver, there is an issue currently. For a workaround see: https://github.com/ClickHouse/clickhouse-odbc/issues/355#issuecomment-841264503

Then, once the driver in built (binary files and/or "package" are created; in macOS it will be a `clickhouse-odbc-***.tar.gz` or `clickhouse-odbc-***.tar.xz` in the build directory), you need to install it (in case of these archives, unpack it) somewhere, and then edit `odbcinst.ini` and `odbc.ini` files accordingly. For more info on that see: https://github.com/ClickHouse/clickhouse-odbc#configuration and https://github.com/ClickHouse/clickhouse-odbc#configuration-iodbc.

**Comment by madcat1991** [comment]
Hi @nlc10, a friend of mine has recently tried to install the driver with a new version of Tableau Desktop on macOS. Unfortunately, he didn't manage to make it work. Probably you should try suggestions from @traceon. Please give here a feedback if it works.
