### ISSUE TITLE
Не работает ODBC connection в Visual Studio для модели SSAS Tabular

### ISSUE THREAD

**Issue by OlgaChukleeva** [yandex/clickhouse-odbc#22]
Добрый день. Требуется загрузить данные из ClickHouse в табличную модель (разрабатываем ее с помощью ssas tabular в Visual Studio).
При тестировании соединения Visual Studio вываливается с ошибкой:
"Problem signature:
  Problem Event Name:  BEX
  Application Name:  devenv.exe
  Application Version:  14.0.25420.1
  Application Timestamp:  57685d85
  Fault Module Name:  ODBC32.dll
  Fault Module Version:  6.3.9600.17415
  Fault Module Timestamp:  545046b6
  Exception Offset:  00076051
  Exception Code:  c0000409
  Exception Data:  00000002
  OS Version:  6.3.9600.2.0.0.16.7
  Locale ID:  1049
  Additional Information 1:  4df3
  Additional Information 2:  4df3f3134502cdd8f0201ea0e58fbfb9
  Additional Information 3:  0d10
  Additional Information 4:  0d10de8a9ed5d00e8e5ce3ccf51eda35

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=280262

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt"

Отладка не запускается

devenv.exe' (Win32): Loaded 'C:\Program Files (x86)\ClickHouse ODBC\clickhouseodbcw.dll'. Cannot find or open the PDB file.
'devenv.exe' (Win32): Loaded 'C:\Program Files (x86)\ClickHouse ODBC\PocoFoundation.dll'. Module was built without symbols.
'devenv.exe' (Win32): Loaded 'C:\Program Files (x86)\ClickHouse ODBC\PocoNet.dll'. Module was built without symbols.

Подскажите, пожалуйста, в чем может быть проблема?

**Comment by artpaul** [comment]
Честно говоря, совершенно не понятно, что за проблема, но если у вас есть Visual Studio, то вы можете собрать драйвер из исходников и запустить интерактивную отладку.

**Comment by chipitsine** [comment]
Ольга, можете попробовать инсталлятор, с отладочными символами 

https://ci.appveyor.com/project/chipitsine/clickhouse-odbc/build/1.0.80/artifacts

?

(там только x64 сборка, отладочные символы есть для Unicode, для ANSI нет)

**Comment by chipitsine** [comment]
ой, кажется, вы используете 32 битную версию. сейчас под нее соберу отладочный инсталятор

**Comment by chipitsine** [comment]
https://ci.appveyor.com/project/chipitsine/clickhouse-odbc/build/1.0.84/artifacts - отладочный инсталятор для x86 (как у вас), попробуете ?

**Comment by artpaul** [comment]
Пожалуйста, переоткройте, если с самой свежей версией драйвера данная проблема всё ещё актуальна.
