### ISSUE TITLE
ODBC parameters substitution

### ISSUE THREAD

**Issue by aadim** [yandex/clickhouse-odbc#33]
There's a problem with query parameters substitution in the driver. For example here's a query in Tableau:

```
SELECT  
    site, date, toString(date) as date1, uniqExact(uid) as uv,  uniq(uid) as uv0, count() as vv   
from 
    groot3.content_watch
where 
    date>= <Parameters.date_from> and date< <Parameters.date_to>
group by site, date, toString(date)
```
The driver receives a translated query:

```
SELECT  
    site, date, toString(date) as date1, uniqExact(uid) as uv,  uniq(uid) as uv0, count() as vv   
from 
    groot3.content_watch
where 
    date>= {d '2017-07-01'} and date< {d '2017-07-02'}
group by site, date, toString(date)
```

and it must convert d'2017-07-01' statement to a correct Clickhouse date but is does not and there's an error executing this query.

**Comment by artpaul** [comment]
Hi,
thanks for the report. I'll fix it in a few days.

**Comment by artpaul** [comment]
Please try new release, should work.
https://github.com/yandex/clickhouse-odbc/releases/latest

**Comment by aadim** [comment]
Hi!

I have reinstalled the driver but have the same error

**Comment by artpaul** [comment]
Could you copy here the text of the error message?

**Comment by aadim** [comment]
Here's the query generated by driver and send to the CH server:

```
SELECT *
FROM (
  SELECT  
      site, date, toString(date) as date1, uniqExact(uid) as uv,  uniq(uid) as uv0, count() as vv   
  from 
      groot3.content_watch
  where 
      date>= {d '2017-07-01'} and date< '2017-08-10'
  group by site, date, toString(date)
) `Custom_SQL_Query`
LIMIT 1 
```

The error is 

```
Code: 62, e.displayText() = DB::Exception: Syntax error: failed at position 191 (line 8, col 14): {d '2017-07-01'} and date< '2017-08-10'
  group by site, date, toString(date)
) `Custom_SQL_Query`
LIMIT 1 . Unrecognized token, e.what() = DB::Exception

```

**Comment by artpaul** [comment]
Are you sure what you are connecting with latest version of driver? Because in this query substring {d '2017-07-01'} should be correctly replaced with toDate('2017-07-01').

**Comment by artpaul** [comment]
Please try new one:
https://github.com/yandex/clickhouse-odbc/releases/tag/2017-09-13

**Comment by aadim** [comment]
Seems to be OK! Tanks. I'll keep tuning Tableau integration.
