### ISSUE TITLE
Strings truncation

### ISSUE THREAD

**Issue by aadim** [yandex/clickhouse-odbc#34]
We have a dictionary with string values. When I select a value using JDBC driver everything is OK:

```
select dictGetString('subsite', 'title', toUInt64(1303))
```

"Gambit-html5-android"

The same query executed by the ODBC driver in Tableau yelds "Gambit-html5-an". All strings are truncated to first 15 characters. Same is true for ordinary non-dictionary tables.

**Comment by artpaul** [comment]
Please try yet another new release:
https://github.com/yandex/clickhouse-odbc/releases/tag/2017-09-13-2

**Comment by aadim** [comment]
it's fine
