### ISSUE TITLE
odbc driver building on MacOS

### ISSUE THREAD

**Issue by santaux** [yandex/clickhouse-odbc#35]
Hello,

Is it possible to build this driver on MacOS? I've tried to built this driver on MacOS but my try failed. 

First, you need to replace this: `#include <malloc.h>` with this `#include "/usr/include/malloc/malloc.h"` in all files, because only including with absolute path works (I don't know why).

Second, you need to replace `SQLColAttribute` constant everywhere with some other name (e.g. `SQLColumnAttribute`), because this name already used by some of the SQL libraries on MacOS.

Third, some compilation options (e.g. `-static-libgcc`) and some others don't support on MacOS.

And the last thing, into the ./driver/CMakeFiles/clickhouse-odbc.dir/cmake_clean.cmake file we see "clickhouse-odbc.dylib" removing. This strange because the .dylib file is the goal we want to reach after building.

And then we successfully get clickhouse-odbc.dylib driver and connect it with odbc.ini file we get "Segmentation fault" after using it.

May be I'm wrong and this driver could be built only on Linux, but may be this information will help somebody.

Thanks.

**Comment by artpaul** [comment]
@ztlpn Alex, have you tried to build the driver under MacOS?

**Comment by kszucs** [comment]
@artpaul With the current master and installed unixodbc - `brew install unixodbc`

Configuring look okay

```bash
$ cmake ..
-- CMAKE_BUILD_TYPE: RelWithDebInfo
-- Using Poco: /Users/krisz/Workspace/clickhouse-odbc/contrib/poco/Foundation/include/;/Users/krisz/Workspace/clickhouse-odbc/contrib/poco/Util/include/;/Users/krisz/Workspace/clickhouse-odbc/contrib/poco/Net/include/ : PocoFoundation,PocoUtil,PocoNet
-- Building for: Darwin-16.7.0 x86_64
-- Poco package version: 2.0.0
-- Building static libraries
-- Building without tests
-- Building without samples
-- Build with using internal copy of sqlite, libz, pcre, expat, ...
-- Found APR: /usr/lib/libapr-1.dylib
-- Found APRUTIL: /usr/lib/libaprutil-1.dylib
-- Found APACHE: /usr/include/apache2
-- CMake 3.9.3 successfully configured Poco using Unix Makefiles generator
-- Installation target path: /usr/local
--
-- Generated with config types:
-- Setting Poco build type - RelWithDebInfo
--
-- C_FLAGS:  =
-- CMAKE_C_FLAGS_DEBUG:=-g   -D_DEBUG
-- CMAKE_C_FLAGS_RELEASE:=-O3 -DNDEBUG
-- CMAKE_C_FLAGS_MINSIZEREL:=-Os -DNDEBUG
-- CMAKE_C_FLAGS_RELWITHDEBINFO:=-O2 -g -DNDEBUG
--
--
-- CXX_FLAGS:= -std=c++14 -O2 -g -fvisibility-inlines-hidden
-- CMAKE_CXX_FLAGS_DEBUG:=-g -D_DEBUG
-- CMAKE_CXX_FLAGS_RELEASE:=-O3 -DNDEBUG
-- CMAKE_CXX_FLAGS_MINSIZEREL:=-Os -DNDEBUG
-- CMAKE_CXX_FLAGS_RELWITHDEBINFO:=-O2 -g -DNDEBUG
-- Building: Util
-- Building: Net
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/krisz/Workspace/clickhouse-odbc/build
```

Making misses `sql.h`

```bash
$ make           
[  1%] Built target gtest-lib
[ 56%] Built target Foundation
[ 65%] Built target Util
[ 95%] Built target Net
[ 96%] Built target clickhouse-odbc-escaping
[ 96%] Building CXX object driver/CMakeFiles/clickhouse-odbc.dir/attr.cpp.o
In file included from /Users/krisz/Workspace/clickhouse-odbc/driver/attr.cpp:1:
In file included from /Users/krisz/Workspace/clickhouse-odbc/driver/connection.h:5:
In file included from /Users/krisz/Workspace/clickhouse-odbc/driver/diagnostics.h:4:
/Users/krisz/Workspace/clickhouse-odbc/driver/platform.h:34:10: fatal error: 'sql.h' file not found
#include <sql.h>
         ^
1 error generated.
make[2]: *** [driver/CMakeFiles/clickhouse-odbc.dir/attr.cpp.o] Error 1
make[1]: *** [driver/CMakeFiles/clickhouse-odbc.dir/all] Error 2
make: *** [all] Error 2
```

Whereas:

```bash
$ ls -lah /usr/local/include | grep sql                                                                                                                                               
lrwxr-xr-x    1 krisz  staff    36B Sep 20 09:02 mysql -> ../Cellar/mysql/5.7.19/include/mysql
lrwxr-xr-x    1 krisz  staff    38B Oct 11 12:22 sql.h -> ../Cellar/unixodbc/2.3.4/include/sql.h
lrwxr-xr-x    1 krisz  staff    41B Oct 11 12:22 sqlext.h -> ../Cellar/unixodbc/2.3.4/include/sqlext.h
lrwxr-xr-x    1 krisz  staff    41B Oct 11 12:22 sqlspi.h -> ../Cellar/unixodbc/2.3.4/include/sqlspi.h
lrwxr-xr-x    1 krisz  staff    43B Oct 11 12:22 sqltypes.h -> ../Cellar/unixodbc/2.3.4/include/sqltypes.h
lrwxr-xr-x    1 krisz  staff    43B Oct 11 12:22 sqlucode.h -> ../Cellar/unixodbc/2.3.4/include/sqlucode.h
```

How should I configure it properly?

**Comment by ztlpn** [comment]
I've managed to build a working driver on macOS - here are my notes of a "works on my laptop" variety:

```
brew install unixodbc
git clone https://github.com/yandex/clickhouse-odbc
cd clickhouse-odbc
git checkout macos-build
git submodule init
git submodule update
mkdir build
cd build
cmake .. -DODBC_LIBRARIES=/usr/local/lib/libodbc.a
make -j8 clickhouse-odbc
```

The `macos-build` branch contains a few code changes that are necessary to build the project but I think are not acceptable in the master.

Also note the `-DODBC_LIBRARIES=/usr/local/lib/libodbc.a` cmake flag. Should be unnecessary, but without it the driver is linked with the wrong odbc library (`/usr/lib/libiodbc.2.dylib` in my case)

@kszucs Your cmake output seems strangely truncated. Here is mine for comparison: https://gist.github.com/ztlpn/542f7d07431d4e2c8310c6d5d90c0a5e

**Comment by santaux** [comment]
@ztlpn, @artpaul Sorry for a late answer. Your instructions work fine 👍 I think you should put them into your Readme file. Thank you.

**Comment by bjornetzold** [comment]
Hi, 
id did exactly what @ztlpn  suggested, but I getting the following output

make -j8 clickhouse-odbc
[ 96%] Built target clickhouse-odbc-escaping
[ 96%] Built target Foundation
[ 96%] Built target Net
[ 96%] Linking CXX shared library clickhouse-odbc.dylib
ld: library not found for -lltdl
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [driver/clickhouse-odbc.dylib] Error 1
make[2]: *** [driver/CMakeFiles/clickhouse-odbc.dir/all] Error 2
make[1]: *** [driver/CMakeFiles/clickhouse-odbc.dir/rule] Error 2
make: *** [clickhouse-odbc] Error 2

**Comment by proller** [comment]
All macos problem should be fixed near https://github.com/yandex/clickhouse-odbc/commit/e062efee13c67f1d4cc56a2e78ad37db8867ed60

```
brew install unixodbc
mkdir -p build; cd build && cmake .. -DODBC_INCLUDE_DIRECTORIES=/usr/local/include -DODBC_LIBRARIES="/usr/local/lib/libodbc.a;/usr/local/lib/libodbcinst.a" && make -j $(nproc || sysctl -n hw.ncpu || echo 4)
```

**Comment by blinkov** [comment]
I've just double checked that from master it builds and works fine under Mac OS.
