### ISSUE TITLE
Timeout в 30 сек.

### ISSUE THREAD

**Issue by sablastik** [yandex/clickhouse-odbc#36]
session.setTimeout(Poco::Timespan(30, 0));

можно сделать этот параметр настраиваемым при создании источника данных?

**Comment by aadim** [comment]
мы так же столкнулись с таймаутами драйвера при подключении Табло к КХ. В JDBC драйвере возможность увеличить таймаут есть. Хотелось бы задавать этот параметр при создании DSN
