### ISSUE TITLE
Int and Date datatypes is not accessible from tableau

### ISSUE THREAD

**Issue by rovboyko** [yandex/clickhouse-odbc#41]
First of all thank you for your product. But I'm faced with issue in using it from Tableau.

Error appears in Tableau while trying to use columns with (Int8,Int16,Int32,Int64,Date,DateTime) datatype in ClickHouse.
ODBC driver tries to send to CH query: 

> SELECT SUM(**{fn CONVERT(test_tableau.i, SQL_BIGINT)}**) AS sum_i_ok FROM test_tableau HAVING (COUNT(1) > 0)

Obviously as a result it returns:

> syntax error

I'm using the last realese of driver (2017-11-07) and ClickHouse v.1.1.54310

**Comment by proller** [comment]
Fixed but not released https://github.com/yandex/clickhouse-odbc/commit/8e8f6065ad3cea7db20355f79f8cd8a92d1fee6b

**Comment by proller** [comment]
Released - https://github.com/yandex/clickhouse-odbc/releases/tag/2018-02-01
