### ISSUE TITLE
ODBC 64 bit not usable from different tools

### ISSUE THREAD

**Issue by Stephane-Thales** [yandex/clickhouse-odbc#50]
Hi All,

I've tested the ODBC 64 bit ( 2017-11-07  018c1d1 installed with the msi on win 7) 
with different tool

- QlikView (Nov 2017 SR1 release) : Can connect but not query "ODBC error Connector reply error: SQL##f - SqlState: HY000, ErrorCode: 1, ErrorMsg: Timeout"

- Query Tool ODBC 64bit (http://www.gpoulose.com/) : Can not connect "Unsuported info type: 15 State:HY000, ErrorCode: 1"

- PowerBI (2.53.4954.621 64-bit December, 2017) : Can not connect "ODBC: ERROR [HY000] Timeout"

Any idea Why ?
How to use the ODBC client in windows with a BI tool ?

thank-you.

**Comment by ztlpn** [comment]
Hi Stephane. Two of the three tools report timeouts on a connection attempt. Can you manually check that your windows machine can reach the ClickHouse server on port 8123? E.g. by pointing your browser at `http://<address_of_your_clickhouse>:8123/` - it should display `Ok.`.

**Comment by Stephane-Thales** [comment]
Hi, My mistake, I tested the client and SSH to the server but didn't test the port 8123. So of course it can't be reached. Let me fix that and try. thank you.
