### ISSUE TITLE
I/O error with Linux driver

### ISSUE THREAD

**Issue by rom8726** [yandex/clickhouse-odbc#58]
Hello!
I built ODBC driver for Linux (build passed without any errors, master branch). But ODBC driver can perform only one query per connection, second query throws I/O error. For example, this error reproduces in isql:
```
vagrant@vagrant-ubuntu-trusty-64:~$ isql clickhouse -v
+---------------------------------------+
| Connected!                            |
|                                       |
| sql-statement                         |
| help [tablename]                      |
| quit                                  |
|                                       |
+---------------------------------------+
SQL> show tables
+------+
| name |
+------+
| test1|
| test2|
+------+
SQLRowCount returns 2
2 rows fetched
SQL> show tables
[S1000][unixODBC]I/O error
SQL> 
```
I use this driver in Erlang application and this error there also happens.
I tried to build driver on local machine, on Vagrant and on CircleCI container. And this error is reproduced everywhere.

**Comment by proller** [comment]
Maybe fixed here - 
https://github.com/yandex/clickhouse-odbc/commit/4a69b7ce2d2d8f85e6c4d9bd58f34065e802f0fe
