### ISSUE TITLE
Как скомпилировать под 32 bit 

### ISSUE THREAD

**Issue by Synoecium** [yandex/clickhouse-odbc#66]
Собственно вопрос, как скомпилировать драйвер под 32битную платформу? Интересует linux Ubuntu 16. В коде проекта в файле arch.cmake нашел проверку такого флага "CMAKE_LIBRARY_ARCHITECTURE", там же кстати предупреждение, что 32бита поддерживается экспериментально, и указал флаг для cmake, но похоже что в генерации ничего не поменялось 
Собственно вопрос, как скомпилировать драйвер под 32битную платформу? Интересует linux Ubuntu 16. В коде проекта в файле arch.cmake нашел проверку такого флага "CMAKE_LIBRARY_ARCHITECTURE", там же кстати предупреждение, что 32бита поддерживается экспериментально, и указал флаг для cmake, но похоже что в генерации ничего не поменялось 
sega@sega-VirtualBox:~/src/ODBC/clickhouse-odbc/build$ cmake .. -DCMAKE_LIBRARY_ARCHITECTURE="i386"
```-- CMAKE_BUILD_TYPE: 
-- Using ltdl: /usr/lib/x86_64-linux-gnu/libltdl.a
-- Using Poco:  : PocoFoundation,PocoUtil,PocoNet
-- Using odbc: /usr/include : /usr/lib/x86_64-linux-gnu/libodbc.a
-- Building for: Linux-4.13.0-36-generic x86_64 x86_64-linux-gnu ; CCACHE=CCACHE_FOUND-NOTFOUND 
-- Linux x86_64 Linux-4.13.0-36-generic 4.13.0-36-generic
-- Poco package version: 1.8.2
-- Checking for C++11 compiler
-- Checking for C++11 compiler - available
-- Checking for C++14 compiler
-- Checking for C++14 compiler - available
-- Setting Poco build type - RELWITHDEBINFO
-- Building static libraries
-- Building without tests & samples
-- Build with using internal copy of sqlite, libz, pcre, expat, ...
-- Platform has THREE PARAM at PTHREAD_SETAFFINITY_NP
-- Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the system variable OPENSSL_ROOT_DIR (missing:  OPENSSL_LIBRARIES OPENSSL_INCLUDE_DIR) 
-- CMake 3.5.1 successfully configured Poco using Unix Makefiles generator
-- Installation target path: /usr/local
-- C_FLAGS:  =
-- CMAKE_C_FLAGS_DEBUG:=-g   -D_DEBUG
-- CMAKE_C_FLAGS_RELEASE:=-O3 -DNDEBUG
-- CMAKE_C_FLAGS_MINSIZEREL:=-Os -DNDEBUG
-- CMAKE_C_FLAGS_RELWITHDEBINFO:=-O2 -g -DNDEBUG
-- 
-- 
-- CXX_FLAGS:= -O2 -g -fvisibility-inlines-hidden
-- CMAKE_CXX_FLAGS_DEBUG:=-g -D_DEBUG
-- CMAKE_CXX_FLAGS_RELEASE:=-O3 -DNDEBUG
-- CMAKE_CXX_FLAGS_MINSIZEREL:=-Os -DNDEBUG
-- CMAKE_CXX_FLAGS_RELWITHDEBINFO:=-O2 -g -DNDEBUG
-- Building: Net
-- compiler C   = /usr/bin/cc  -O2 -g -DNDEBUG
-- compiler CXX = /usr/bin/c++  -O2 -g -fvisibility-inlines-hidden -O2 -g -DNDEBUG
-- LINKER_FLAGS =  
-- Configuring done
-- Generating done
-- Build files have been written to: /home/sega/src/ODBC/clickhouse-odbc/build
```

**Comment by proller** [comment]
1. взять файл из clickhouse - debian/.pbuilderrc и положить его в clickhouse-odbc в debian/.pbuilderrc
2. запустить: sudo DIST=artful       ARCH=i386 pbuilder create —configfile debian/.pbuilderrc && DIST=artful       ARCH=i386 pdebuild —configfile debian/.pbuilderrc
3 - вот он, /var/cache/pbuilder/artful-i386/result/clickhouse-odbc_1.1.1_i386.deb

**Comment by proller** [comment]
https://github.com/yandex/clickhouse-odbc/commit/272d2924faf435edf38198beb3981f168c52c927
теперь пункт 1 можно пропустить
