### ISSUE TITLE
Работа клиентского таймаута в новых версиях драйвера

### ISSUE THREAD

**Issue by aadim** [yandex/clickhouse-odbc#70]
В версиях драйвера после 2017-11-07 перестал корректно задаваться таймаут, который сделали в #36. Если не удается получить от сервера результат в течение 30 сек., то драйвер возвращает ошибку Timeout, не смотря на значительно больший таймаут в настройках ODBC. С драйвером 2017-11-07 таких проблем нет. OC Windows 10 и 8.1. Клиент - Tableau desktop 10.3

**Comment by savelov** [comment]
у меня корректно работает в версии 2018-03-21, проверьте записан ли он в registry, я задавал руками в regedit, параметр Timeout, по умолчанию 30 секунд

**Comment by aadim** [comment]
я проверил на нескольких машинах ключ HKEY_CURRENT_USER\Software\ODBC\ODBC.INI\Clickhouse\Timeout стоит 3000 сек, но таймаут срабатывает через 30 секунд.

**Comment by savelov** [comment]
возможно это clickouse server timeout? в odbc драйвере точно работет, выведено в odbc settings panel, и закодировано достаточно просто, а на сервере я не готов комментирвать - там что-то сложное - [https://github.com/yandex/ClickHouse/commit/ce8de108ed45dd0abe827ae640380e08ebcef611](url)

**Comment by aadim** [comment]
от сервера ничего не поступает, Табло делает запрос, а через 30 секунд разрывает TCP-сессию:

![image](https://user-images.githubusercontent.com/16644384/39131472-265513a0-4718-11e8-94a2-b5be8e307715.png)

**Comment by akonyaev90** [comment]
Есть какие-то новости ?
Столкнулись с этой же проблемой

**Comment by alfiya-s** [comment]
Мы тоже не можем ничего сделать.

**Comment by savelov** [comment]
Это может быть из-за превышения лимитов на сервере и проблемы того что odbc
драйвер не показывает код ошибки

вт, 31 июля 2018 г. в 10:49, alfiya-s <notifications@github.com>:

**Comment by aadim** [comment]
> Это может быть из-за превышения лимитов на сервере и проблемы того что odbc
драйвер не показывает код ошибки

Обратите внимание на скрин из Wireshark, там видно, что через 30 секунд сессию обрывает клиент (Табло), но не сервер, от сервера за эти 30 секунд ничего существенного, что может содержать код ошибки не приходит.

**Comment by hashbash** [comment]
+1
У меня такая же проблема. Очень жду решения.

**Comment by proller** [comment]
Решение тут 
https://github.com/yandex/clickhouse-odbc/commit/7e6f0a583256e45c8d6fc527298bfa5ac8b2c24b
