### ISSUE TITLE
OLE DB provider "STREAM" for linked server "(null)" return message "Требуемое преобразование не поддерживается"

### ISSUE THREAD

**Issue by Algeron21** [yandex/clickhouse-odbc#72]
В MSSQL Server 2017 настроен linked server к ClickHouse через ODBC драйвер, при выполнении запроса и выборе столбцов типа String получаю такую ошибку: OLE DB provider "STREAM" for linked server "(null)" return message "Требуемое преобразование не поддерживается"
Однако, столбцы типа int, date, выводятся без проблем.
Версия MS SQL Server 2017 , Clickhouse v1.1.54370, ODBC драйвер версия x64 от 2018-03-21

**Comment by proller** [comment]
проблема с mssql решена - https://github.com/yandex/clickhouse-odbc/commit/049bc08e9e86f5c8fdb2267213f817c35b2289f4 
Нужно передавать параметр максимального размера строки - stringmaxlength=8000 -
https://github.com/yandex/clickhouse-odbc/blob/master/test/mssql.linked.server.sql#L9
больше 8000 не работает.
С fixedstring должно само заработать и без параметра.
