### ISSUE TITLE
Data source name not found and no default driver 

### ISSUE THREAD

**Issue by dsr301** [yandex/clickhouse-odbc#87]
Hi,

I am trying to connect from c#+.Net throught odbc.

Below is the code i have 
        var builder = new OdbcConnectionStringBuilder();
            builder.Driver = 
                "E:\\MySpace\\Downloads\\clickhouse-odbc-master\\vs\\x64\\clickhouseodbc.dll";
            builder.Add("SERVER", "cagatHDN01.iv.local");
            builder.Add("DATABASE", "default");
            builder.Add("PORT", 8123);
            builder.Add("FRAMED", 0);
            var connection = new OdbcConnection("Driver = Click House ANSI; Host = ***; Port =***");
           //Also tried below
           //var connection = new OdbcConnection(builder.ConnectionString);
            connection.Open();
            return connection;

When I run, I have the exception:
**System.Data.Odbc.OdbcException: 'ERROR [IM002] [Microsoft][ODBC Driver Manager] Data source name not found and no default driver specified'.**

I have also installed the driver and configured as in 
![t](https://user-images.githubusercontent.com/5129304/41473441-4ad71b22-7087-11e8-8deb-154959adc2ed.PNG)

**Comment by proller** [comment]
you should use driver name as in driver manager 
builder.Driver = "clickhouse";
or
builder.Driver = "cliik 2";

https://msdn.microsoft.com/en-gb/library/system.data.odbc.odbcconnectionstringbuilder(v=vs.110).aspx

**Comment by dsr301** [comment]
Thank You! This worked.
