### ISSUE TITLE
Int64 support error

### ISSUE THREAD

**Issue by DandelionWenjing** [yandex/clickhouse-odbc#90]
Hi,
Does this odbc driver support the Int64 type? because I just get error when connect to Power BI if the table have Int64 type.
When will it support the Int64 type?
Thanks.

Wenjing Zhao

**Comment by blinkov** [comment]
There is some support for Int64. Could you please provide the error message and maybe some instruction on how to reproduce it?

**Comment by DandelionWenjing** [comment]
Hi blinkov,
thanks for your reply.
I have build the clickhouse odbc driver in windows and installed successfully. Thanks for the good product.
I have set up the DSN for the clickhouse odbc driver and want to connect clickhouse with Power BI by using ODBC way: 
![image](https://user-images.githubusercontent.com/33156672/42312453-e7ec7aba-8072-11e8-8b5c-cabf559f1238.png)
When I want to load the table, the error shows that:
DataSource.Error: ODBC: ERROR [HY000] Syntax error: Not a valid unsigned integer: -5
Details:
    DataSourceKind=Odbc
    DataSourcePath=dsn=ClickhouseA
    OdbcErrors=Table
![image](https://user-images.githubusercontent.com/33156672/42312513-0eda21cc-8073-11e8-9489-be6bd02cafac.png)
So I check the data type and found that if I changed the type Int64 to Int32, the table can be loaded correctly. 

Thanks.
Wenjing Zhao

**Comment by blinkov** [comment]
Do you have any logs, especially with queries it tries to make? Also which data type Power BI shows for this Int64 column?

Something thinks that Int64 is unsigned, we just need to find what exactly.

**Comment by DandelionWenjing** [comment]
Hi blinkov,

Sorry I can't find logs from the Power BI desktop and also can't confirm the data type because the error happened before the table been loaded into the power bi.
If it possible I can find the log from the odbc driver? 

Thanks.
Wenjing

**Comment by DandelionWenjing** [comment]
Hi blinkov,

I just found that Power BI desktop can enable tracing, so I have output some logs about this error:

SimpleDocumentEvaluator/GetResult<IPreviewValueSource> {"Start":"2018-07-06T03:39:51.7172749Z","Action":"SimpleDocumentEvaluator/GetResult<IPreviewValueSource>","HostProcessId":"22828","Exception":"Exception:\r\nExceptionType: Microsoft.Mashup.Engine1.Runtime.ValueException, Microsoft.MashupEngine, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35\r\nMessage: **[DataSource.Error] ODBC: ERROR [HY000] Syntax error: Not a valid unsigned integer: -5**\r\nStackTrace:\n   at Microsoft.Mashup.Evaluator.SimpleDocumentEvaluator.<>c__DisplayClass2.<BeginGetResult>b__0(EvaluationResult2`1 result)\r\n\r\nInnerException\r\nException:\r\nExceptionType: Microsoft.Mashup.Engine1.Library.Odbc.Interop.OdbcException, Microsoft.MashupEngine, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35\r\nMessage: ERROR [HY000] Syntax error: Not a valid unsigned integer: -5\r\nStackTrace:\n   at Microsoft.Mashup.Engine1.Library.Odbc.Interop.OdbcUtils.HandleError(OdbcHandle hrHandle, RetCode retcode)\r\n   at Microsoft.Mashup.Engine1.Library.Odbc.OdbcPageReader.OdbcPage.GetData(SQL_C cType, Int32 rowIndex, Int32 columnIndex, Int64 pos)\r\n   at Microsoft.Mashup.Engine1.Library.Odbc.OdbcPageReader.OdbcPage.LoadCellData(ColumnInfo columnInfo, Column column, Int32 rowIndex, Int32 rowSetIndex, Int32 columnIndex)\r\n   at Microsoft.Mashup.Engine1.Library.Odbc.OdbcPageReader.OdbcPage.SyncColumnsPage(Byte* boundColumnsDataPtr)\r\n   at Microsoft.Mashup.Engine1.Library.Odbc.OdbcPageReader.OdbcPage.Read(OdbcStatementHandle statement, RowRange rowRange)\r\n   at Microsoft.Mashup.Engine1.Library.Odbc.OdbcPageReader.Read(OdbcPage page)\r\n   at Microsoft.OleDb.Serialization.PageReaderDataReader.Read()\r\n   at Microsoft.Mashup.Engine1.Library.Odbc.OdbcCachingService.OdbcCachingConnection.DataTableFrom(IDataReader reader)\r\n   at Microsoft.Mashup.Engine1.Library.Odbc.OdbcCachingService.OdbcCachingConnection.Cache(String[] keyParts, Func`2 func)\r\n   at Microsoft.Mashup.Engine1.Library.Odbc.UserOverrideOdbcService.UserOverrideOdbcConnection.GetColumns(String catalogName, String schemaName, String tableName)\r\n   at Microsoft.Mashup.Engine1.Library.Odbc.OdbcColumnInfoCollection.<EnsureInitialized>b__0(IOdbcConnection connection)\r\n   at Microsoft.Mashup.Engine1.Library.Odbc.OdbcDataSource.<>c__DisplayClassa.<Connect>b__9(IOdbcConnection connection)\r\n   at Microsoft.Mashup.Engine1.Library.Odbc.OdbcDataSource.<>c__DisplayClass7`1.<Connect>b__6()\r\n   at Microsoft.Mashup.Engine1.Library.Common.DbExceptionHandler.RunWithRetryGuard[T](Int32 maxRetryAttempts, Func`1 action)\r\n   at Microsoft.Mashup.Engine1.Library.Common.DbExceptionHandler.Invoke[T](Int32 maxRetry, Func`1 action)\r\n\r\n\r\n\r\n\r\n","ProductVersion":"2.59.5135.781 (PBIDesktop)","ActivityId":"652a35c2-723e-4dd6-a966-337fe8a23459","Process":"Microsoft.Mashup.Container.NetFX40","Pid":6928,"Tid":1,"Duration":"00:00:00.4673939"}

SimpleDocumentEvaluator/GetResult<IPreviewValueSource> {"Start":"2018-07-06T03:39:54.2522326Z","Action":"SimpleDocumentEvaluator/GetResult<IPreviewValueSource>","HostProcessId":"22828","Exception":"Exception:\r\nExceptionType: Microsoft.Mashup.Engine1.Runtime.ValueException, Microsoft.MashupEngine, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35\r\nMessage: [DataSource.Error] ODBC: ERROR [HY000] Syntax error: Not a valid unsigned integer: -5\r\nStackTrace:\n   at Microsoft.Mashup.Evaluator.SimpleDocumentEvaluator.<>c__DisplayClass2.<BeginGetResult>b__0(EvaluationResult2`1 result)\r\n\r\nInnerException\r\nException:\r\nExceptionType: Microsoft.Mashup.Engine1.Library.Odbc.Interop.OdbcException, Microsoft.MashupEngine, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35\r\nMessage: ERROR [HY000] Syntax error: Not a valid unsigned integer: -5\r\nStackTrace:\n   at Microsoft.Mashup.Engine1.Library.Odbc.Interop.OdbcUtils.HandleError(OdbcHandle hrHandle, RetCode retcode)\r\n   at Microsoft.Mashup.Engine1.Library.Odbc.OdbcPageReader.OdbcPage.GetData(SQL_C cType, Int32 rowIndex, Int32 columnIndex, Int64 pos)\r\n   at Microsoft.Mashup.Engine1.Library.Odbc.OdbcPageReader.OdbcPage.LoadCellData(ColumnInfo columnInfo, Column column, Int32 rowIndex, Int32 rowSetIndex, Int32 columnIndex)\r\n   at Microsoft.Mashup.Engine1.Library.Odbc.OdbcPageReader.OdbcPage.SyncColumnsPage(Byte* boundColumnsDataPtr)\r\n   at Microsoft.Mashup.Engine1.Library.Odbc.OdbcPageReader.OdbcPage.Read(OdbcStatementHandle statement, RowRange rowRange)\r\n   at Microsoft.Mashup.Engine1.Library.Odbc.OdbcPageReader.Read(OdbcPage page)\r\n   at Microsoft.OleDb.Serialization.PageReaderDataReader.Read()\r\n   at Microsoft.Mashup.Engine1.Library.Odbc.OdbcCachingService.OdbcCachingConnection.DataTableFrom(IDataReader reader)\r\n   at Microsoft.Mashup.Engine1.Library.Odbc.OdbcCachingService.OdbcCachingConnection.Cache(String[] keyParts, Func`2 func)\r\n   at Microsoft.Mashup.Engine1.Library.Odbc.UserOverrideOdbcService.UserOverrideOdbcConnection.GetColumns(String catalogName, String schemaName, String tableName)\r\n   at Microsoft.Mashup.Engine1.Library.Odbc.OdbcColumnInfoCollection.<EnsureInitialized>b__0(IOdbcConnection connection)\r\n   at Microsoft.Mashup.Engine1.Library.Odbc.OdbcDataSource.<>c__DisplayClassa.<Connect>b__9(IOdbcConnection connection)\r\n   at Microsoft.Mashup.Engine1.Library.Odbc.OdbcDataSource.<>c__DisplayClass7`1.<Connect>b__6()\r\n   at Microsoft.Mashup.Engine1.Library.Common.DbExceptionHandler.RunWithRetryGuard[T](Int32 maxRetryAttempts, Func`1 action)\r\n   at Microsoft.Mashup.Engine1.Library.Common.DbExceptionHandler.Invoke[T](Int32 maxRetry, Func`1 action)\r\n\r\n\r\n\r\n\r\n","ProductVersion":"2.59.5135.781 (PBIDesktop)","ActivityId":"23457dd1-1048-42fe-85e7-562a319abfbb","Process":"Microsoft.Mashup.Container.NetFX40","Pid":4512,"Tid":1,"Duration":"00:00:01.7502005"}

Hope it would help. 
Thanks.
Wenjing Zhao

**Comment by DandelionWenjing** [comment]
Hi blinkov,
I have upgraded the windows sdk to the version 10.0.17314.0 and the platform toolkit to the 141 when I build the driver in the windows. Will this upgrade effect the build and installation? Thanks.

Wenjing Zhao

**Comment by DandelionWenjing** [comment]
Hi @blinkov ,
I have got the warning when I tried to build the driver again to find the solution.
![image](https://user-images.githubusercontent.com/33156672/42549821-d0199a48-8500-11e8-8c7a-851c7616a01c.png)
There are some warnings when transfer the data type from the Poco::Uint64 to uint8_t, do you think is this the key point of my problems? Maybe the incompatible with the Poco library because I have missed something?
Thanks a lot.

Wenjing

**Comment by DandelionWenjing** [comment]
Hi @proller ,
I have tested that "Int64" and "Uint64" Type will both get the same error as I have showed.
![image](https://user-images.githubusercontent.com/33156672/42609416-202a363c-85bf-11e8-97e0-c3d8872566cf.png)
I don't know if I have missed something and how to solve it or there are some errors.

Thanks.

Wenjing Zhao

**Comment by DandelionWenjing** [comment]
Hi @proller ,
I have adopted the build_vs.bat way to build and generate the .msi successfully, the poco problem is warning but not error. While I just tried the cmake way to build and got the error about Poco Lib:

connection.cpp(16): fatal error C1083: can not open file : “Poco/Net/AcceptCertificateHandler.h”: No such file or directory

So which release version have you used for the poco ? I doubt that the Int64 type error is come from the poco lib:
![image](https://user-images.githubusercontent.com/33156672/42610700-500a8efa-85c5-11e8-8f86-87749f3e16f5.png)
I can try that version again to find out if the error come from the poco lib.
Thanks,

Wenjing

**Comment by DandelionWenjing** [comment]
Hi @proller @blinkov ,
This error have been averted if I modified the code to avoid using Poco Library involved Int64 type. I don't know why but the Poco Library support for some of the odbc driver test tools is not that effective including Power BI. If I try to use the C++ standard Int64 type, the problem is gone.

Thanks for reply.
Wenjing Zhao

**Comment by proller** [comment]
https://github.com/yandex/clickhouse-odbc/commit/9f5e78852d2c7731d23aa0a614c1149e7c69cabb
