### ISSUE TITLE
ODBC with Tableau Nullable Integers

### ISSUE THREAD

**Issue by napaHouk** [yandex/clickhouse-odbc#91]
Hi, I'm faced with a problem. When the Tableau tries to read data from the Nullable Int or UInt columns containing Null then it produces the following error "Syntax error: Not a valid integer: ᴺᵁᴸᴸ." (or unsigned integer in other case). There are no problems wtih tables where Null is missing. Is there any method to avoid such error except replace all Nulls in data?
Trying with:
Tableau 10.4,
Tableau 2018.1,
ClickHouse 1.1.54385,
ClickHouse 1.1.54388
![tableau](https://user-images.githubusercontent.com/40859739/42323849-326e535a-806a-11e8-9a5e-9865a275bc5c.jpg)

**Comment by alexey-milovidov** [comment]
It looks like that ODBC driver doesn't support NULLs at all.
Look in `ODBCDriverBlockInputStream.cpp`. It requires protocol change.

**Comment by tru1** [comment]
Думаю это пофиксит проблему. 

RETCODE SQL_API impl_SQLGetData(HSTMT statement_handle,
    SQLUSMALLINT column_or_param_number,
    SQLSMALLINT target_type,
    PTR out_value,
    SQLLEN out_value_max_size,
    SQLLEN * out_value_size_or_indicator)
{
    //LOG(__FUNCTION__);

    return doWith<Statement>(statement_handle, [&](Statement & statement) -> RETCODE {
        if (column_or_param_number < 1 || column_or_param_number > statement.result.getNumColumns())
            throw std::runtime_error("Column number is out of range.");

        size_t column_idx = column_or_param_number - 1;

        //LOG("column: " << column_idx << ", target_type: " << target_type << ", out_value_max_size: " << out_value_max_size);

        const Field & field = statement.current_row.data[column_idx];

		// if the column is nullable and data is NULL
		if (field.data.compare("NULL") == 0)
		{
			*out_value_size_or_indicator = SQL_NULL_DATA;
			return SQL_SUCCESS;
		}

**Comment by tru1** [comment]
Ну и продолжение с нан

            case SQL_C_FLOAT:
				if (field.data.compare("nan") == 0)
					return fillOutputNumber<float>(NAN, out_value, out_value_max_size, out_value_size_or_indicator);
				else
					return fillOutputNumber<float>(field.getFloat(), out_value, out_value_max_size, out_value_size_or_indicator);

            case SQL_C_DOUBLE:
				if (field.data.compare("nan") == 0)
					return fillOutputNumber<double>(NAN, out_value, out_value_max_size, out_value_size_or_indicator);
				else
					return fillOutputNumber<double>(field.getDouble(), out_value, out_value_max_size, out_value_size_or_indicator);

**Comment by proller** [comment]
https://github.com/yandex/clickhouse-odbc/pull/79

**Comment by proller** [comment]
https://github.com/yandex/clickhouse-odbc/commit/5b74c3079a2eea34ca0bf90c52e93751b2c74aa9
https://github.com/yandex/clickhouse-odbc/releases/tag/2018-09-03

**Comment by proller** [comment]
Use clickhouse server 18.10.3+
